from fastapi import APIRouter

from .data_representations import data_representations_router
from .stationarity_testing import stationary_testing_router
from .autocorrelation_diagnosis import autocorrelation_diagnosis_router
from .descriptive_statistics import descriptive_statistics_router

preliminary_diagnosis_router = APIRouter(prefix='/preliminary_diagnosis', tags=['Предварительная диагностика'])

preliminary_diagnosis_router.include_router(stationary_testing_router)
preliminary_diagnosis_router.include_router(autocorrelation_diagnosis_router)
preliminary_diagnosis_router.include_router(descriptive_statistics_router)
preliminary_diagnosis_router.include_router(data_representations_router)
